//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.example.androidannotationstest;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;

public final class MyReceiver_
    extends MyReceiver
{

    public final static String ACTIONS_ANOTHER_ACTION = "anotherAction";
    public final static String NAME_EXTRA = "name";
    public final static String VALUE_LONG_EXTRA = "valueLong";
    public final static String ACTIONS_MY_ACTION = "myAction";
    public final static String VALUE_STRING_EXTRA = "valueString";

    @Override
    public void onReceive(Context context, Intent intent) {
        init_(context);
        super.onReceive(context, intent);
        String action = intent.getAction();
        if (ACTIONS_ANOTHER_ACTION.equals(action)) {
            Bundle extras_ = ((intent.getExtras()!= null)?intent.getExtras():new Bundle());
            String valueString = extras_.getString(NAME_EXTRA);
            long valueLong = extras_.getLong(VALUE_LONG_EXTRA);
            MyReceiver_.this.anotherAction(context, valueString, valueLong);
            return ;
        }
        if (ACTIONS_MY_ACTION.equals(action)) {
            Bundle extras_ = ((intent.getExtras()!= null)?intent.getExtras():new Bundle());
            String valueString = extras_.getString(VALUE_STRING_EXTRA);
            MyReceiver_.this.myAction(valueString, context);
            return ;
        }
    }

    private void init_(Context context) {
    }

}
